services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_USER_SERVICE_URL=http://localhost:3000
      - VITE_QUESTION_SERVICE_URL=http://localhost:3001
      - VITE_MATCHING_SERVICE_URL=http://localhost:3002
      - VITE_COLLAB_SERVICE_URL=http://localhost:3003
    depends_on:
      - matching-service
      - user-service
      - question-service
      - collaboration-service

  user-service:
    build: ./user-service
    ports:
      - "3000:3000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}

  matching-service:
    build: ./matching-service
    ports:
      - "3002:3002"
    env_file:
      - ./matching-service/.env.docker
    environment:
      - USER_SERVICE_URL=http://user-service:3000
      - QUESTION_SERVICE_URL=http://question-service:3001
      - COLLABORATION_SERVICE_URL=http://collaboration-service:3003
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - user-service
      - question-service
      - collaboration-service


  collaboration-service:
    build: ./collaboration-service
    ports:
      - "3003:3003"
    env_file:
      - ./collaboration-service/.env
    environment:
      - PORT=3003
      - QUESTION_SERVICE_URL=http://question-service:3001
      - MATCHING_SERVICE_URL=http://matching-service:3002
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - question-service

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
