import Anthropic from "@anthropic-ai/sdk";

/**
 * Sends a prompt to the Claude (Anthropic) API and retrieves a generated response.
 *
 * Returns:
 * - Plain text response generated by Claude
 *
 * @param {string} prompt - Input prompt sent to the AI model
 * @returns {string} Generated response text
 */
export const callClaude = async (prompt) => {
  const anthropic = new Anthropic({
    apiKey: process.env.CLAUDE_API_KEY,
  });

  const response = await anthropic.messages.create({
    model: "claude-sonnet-4-6",
    max_tokens: 300,
    messages: [
      {
        role: "user",
        content: prompt,
      },
    ],
  });

  return response.content[0].text;
};